### PR TITLE
 Initial fastANI and dnadiff snakemake workflows

### LINKED ISSUE #9: Create initial snakemake workflow for fastANI
The goal of `pyani-plus` is to facilitate genome comparison using ANI. Since various algorithms exist for ANI calculation (eg. aniM, aniB, fastANI), `pyani-plus` will aim to provide different methods for comparing genomes. 

For `fastANI` integration, we need to:

1. **Update Makefile to Install fastANI:**
   Update the Makefiles to include the installation of fastANI, ensuring that the necessary dependencies are installed.

2. **Write Initial Workflow to Generate Appropriate Files:**
   Develop the initial workflow to generate the required files (`fastANI`). 

3. **Create Test Set of Target Outputs:**
   Generate a test set comprising target output files generated by the fastANI workflow. These target outputs will serve as benchmarks for validating the accuracy and functionality of the implementation.

4. **Test the Workflow with pytest:**
   Test the workflow to ensure that it runs with our errors and produces the expected output.

### LINKED ISSUE #12: Create initial `snakemake` workflow for `dnadiff` method
As previously mentioned in #9, different methods exist for ANI calculations. One of many goals for `pyani_plus` is to replicate the ANI values provided by `dnadiff`.

To integrate `dnadiff`, we need to:

1. **Write Initial Workflow to Generate Appropriate Files**: Develop the initial workflow to produce the required files. Specifically, we need to use `nucmer` to generate `.delta` files, `delta-filter` to create `.filter` files, and `show-diff` to generate `.rdiff` files.

2. **Create Test Set of Target Outputs**: Generate a test set comprising target output files produced by all `nucmer` wrappers (e.g., `nucmer`, `delta-filter`, and `show-diff`). These target outputs will serve as benchmarks to validate that the workflow produces all expected outputs and that the content of the generated files is as expected.

3. **Test the Workflow with pytest**: Test the entire `snakemake` workflow using `pytest` to ensure it runs without errors and that all expected outputs are generated.

NOTE: There is no need to update `Make` file to install any dependencies. This is because all dependencies required  for the `dnadiff` method are the same as those needed for the `ANIm` method.

### PR DESCRIPTION
**Pull request by kiepczi**
Initial snakemake workflow for integration of `fastANI` and `dnadiff`, fixes #9 and fixes #12
The code includes:
- Updates to makefiles to install all dependencies (eg. `fastANI`)
- Initial workflows to generate appropriate files
- Test sets of target outputs including `bash` scripts used to generate them
- `pytests` used to check functionality of the code

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [X] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality not to work as expected)
- [X] This change requires a documentation update
- [ ] This is a documentation update

## Action Checklist

- [X] Work on a single issue/concept (if there are multiple separate issues to address, please use a separate pull request for each)
- [X] Fork the `pyani-plus` repository under your own account (please [allow write access for repository maintainers](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork))
- [X] Set up an appropriate development environment (please see `CONTRIBUTING.md` for this repository)
- [X] Create a new branch with a short, descriptive name
- [X] Work on this branch
  - [X] style guidelines have been followed (please see `CONTRIBUTING.md` for this repository)
  - [X] new code is commented, especially in hard-to-understand areas
  - [ ] corresponding changes to documentation have been made
  - [X] tests for the change have been added that demonstrate the fix or feature works
- [X] Test locally with `pytest-plus -v` **non-passing code will not be merged**
- [X] Rebase against `origin/master`
- [X] Check changes with linting/formatting tools before submission (please see `CONTRIBUTING.md` for this repository)
- [X] Commit branch
- [X] Submit pull request, describing the content and intent of the pull request
- [X] Request a code review
- [X] Continue the discussion at [`Pull requests` section](https://github.com/widdowquinn/pyani-plus/pulls) in the `pyan-plus` repository

### CODE REVIEW

**Comment by widdowquinn** [comment]
There's an odd thing about the file `tests/fixtures/dnadiff/targets/show_diff/NC_014100_vs_NC_002696.rdiff` in commit 94ff62f. The autogenerated `.rdiff` file has changed at l.58-60:

```text
gi|295687459|ref|NC_014100.1|	GAP	185632	185970	339	339	0
gi|295687459|ref|NC_014100.1|	GAP	188180	188546	367	66	301
gi|295687459|ref|NC_014100.1|	JMP	188669	188546	-122
gi|295687459|ref|NC_014100.1|	INV	188664	188701	38
gi|295687459|ref|NC_014100.1|	BRK	189126	192447	3322
```

in the old file becomes

```
gi|295687459|ref|NC_014100.1|	GAP	185632	185970	339	339	0
gi|295687459|ref|NC_014100.1|	JMP	188180	188546	367
gi|295687459|ref|NC_014100.1|	JMP	188664	188546	-117
gi|295687459|ref|NC_014100.1|	INV	188669	188701	33
gi|295687459|ref|NC_014100.1|	BRK	189126	192447	3322
```

There may be a sensible reason for this (filtered file vs raw diff file input earlier?) but I don't see what it is, yet.

**Review by widdowquinn — CHANGES_REQUESTED** [review]
`generate_target_dnadiff_files.py`

Please can we restructure slightly so that a single `for` loop runs to generate each of the test files. It looks like defining an array with `GENOME_1_vs_GENOME_2` for each comparison would be sufficient. This would reduce the opportunity for copy/paste bugs to creep in if we extent.

**Review by widdowquinn — CHANGES_REQUESTED** [review]
In `compare_show_files()` the `strict=False` option means we may miss file differences where additional lines are present. We should use `strict=True`, instantiate the `zip()` result as a list, and wrap in a `try/except` clause, catching the `ValueError` to return `False` - this exits quickly if there are different numbers of lines.

Otherwise looping over the lines would be OK.

**Comment by kiepczi** [comment]
I've made changes to reflect all proposed changes, such as:

- Used a `for` loop to generate all fixtures for future testing. These changes apply to fixtures used for all methods, not just `dnadiff` files.
- `strict=False` is no longer used to compare the content of expected vs. generated files. Instead, as suggested, `strict=True` was used along with a `try/except` block to catch any potential differences in file lengths.

> There's an odd thing about the file `tests/fixtures/dnadiff/targets/show_diff/NC_014100_vs_NC_002696.rdiff` in commit [94ff62f](https://github.com/pyani-plus/pyani-plus/commit/94ff62f455460333502b081cc4cfb7616459e209). The autogenerated `.rdiff` file has changed at l.58-60:


I also looked into this, and interestingly, there is no difference between using `filter` files or raw `delta` files as input. I generated 10 `.rdiff` files with a `for` loop using the same inputs and parameters, and they returned both versions. This might need more investigation.

**Comment by kiepczi** [comment]
> I also looked into this, and interestingly, there is no difference between using `filter` files or raw `delta` files as input. I generated 10 `.rdiff` files with a `for` loop using the same inputs and parameters, and they returned both versions. This might need more investigation.

You can find all command lines, and generated data [here](https://github.com/user-attachments/files/15835201/dnadiff.zip).

**Comment by widdowquinn** [comment]
> > I also looked into this, and interestingly, there is no difference between using `filter` files or raw `delta` files as input. I generated 10 `.rdiff` files with a `for` loop using the same inputs and parameters, and they returned both versions. This might need more investigation.
> 
> You can find all command lines, and generated data [here](https://github.com/user-attachments/files/15835201/dnadiff.zip).

This seems… not our fault. There may be something nondeterministic going on within `dnadiff`. In discussion around the code we recalled that graph construction can involve a tie/choice between two plausible joins, and there is possibly an element of randomness in which gets chosen, with knock-on effects on the `.rdiff` file that gets produced.

We clearly can't rely on stable output for at least some input comparisons. The question is what to do?

I think that maybe we ought to drop the unusual comparisons from this test in the first instance. But what we can do is put this in a different set of "dodgy inputs" where we can `XFAIL`/skip or similar, just to keep around that this is an aberrant example that sometimes fails.

**Comment by widdowquinn** [comment]
We might want to wrap that last test in `pytest` `XFAIL` mark:

> An xfail means that you expect a test to fail for some reason. A common example is a test for a feature not yet implemented, or a bug not yet fixed. When a test passes despite being expected to fail (marked with pytest.mark.xfail), it’s an xpass and will be reported in the test summary.

**Comment by widdowquinn** [comment]
I've merged `main` into `issue_9` - a problem we didn't solve on the Monday (2024-07-29), but I think we need to work on a consistent naming scheme for tests. I'm getting confused looking at fixtures like:

```python
@pytest.fixture()
def config_delta_args(
    dnadiff_nucmer_targets_delta_outdir: Path,
    input_genomes_small: Path,
) -> dict:
    """Return configuration settings for testing snakemake delta rule.

    We take the output directories for the MUMmer delta output and the
    small set of input genomes as arguments.
    """
    return {
        "outdir": dnadiff_nucmer_targets_delta_outdir,
        "indir": str(input_genomes_small),
        "cores": 8,
        "mode": "mum",
    }
```

in `test_snakemake_dnadiff_workflow.py`

where it's clearly a `dnadiff`-related fixture, but that's not indicated in the name `config_delta_args`. There's a similar issue with `test_snakemake_rule_delta()` which isn't clearly `dnadiff`-related. To some extent I get that it's implicit in the filename, but while reading through the code I find myself getting a bit lost, as the docstrings aren't telling me exactly what's going on and the function names are ambiguous.

**Comment by widdowquinn** [comment]
I'm currently getting a failure on `test_snakemake_rule_show_coords()`, claiming that something isn't right in the snakemake workflow file. The `test_snakemake_rule_delta()`, `test_snakemake_rule_filter()`, and `test_snakemake_show_diff()` tests all pass. The reported error has the format below and is thrown for all jobs:

```text
ERROR    snakemake.logging:logging.py:592 Error in rule delta:
    jobid: 20
    output: /Users/lpritc/Documents/Development/GitHub/pyani-plus/pyani-plus/tests/dnadiff_show_coords_output/NC_011916_vs_NC_014100.delta
```

**Comment by widdowquinn** [comment]
The error seems to be coming from the `delta` rule in the snakemake workflow. When the `show_coords` rule is propagated back to `delta`, this kind of error is thrown:

```bash
/bin/bash: -c: line 0: syntax error near unexpected token `('
/bin/bash: -c: line 0: `set -euo pipefail;  nucmer -p /Users/lpritc/Documents/Development/GitHub/pyani-plus/pyani-plus/tests/dnadiff_show_coords_output/NC_014100_vs_NC_011916 --maxmatch PosixPath('/Users/lpritc/Documents/Development/GitHub/pyani-plus/pyani-plus/tests/fixtures/sequences')/NC_014100.* PosixPath('/Users/lpritc/Documents/Development/GitHub/pyani-plus/pyani-plus/tests/fixtures/sequences')/NC_011916.*'
```

Inspecting the `delta` rule, we see

```python
rule delta:
    params:
        indir=config["indir"],
        outdir=config["outdir"],
    output:
        "{outdir}/{genomeA}_vs_{genomeB}.delta",
    run:
        shell(
            "nucmer -p {wildcards.outdir}/{wildcards.genomeA}_vs_{wildcards.genomeB} --maxmatch {params.indir}/{wildcards.genomeA}.* {params.indir}/{wildcards.genomeB}.*"
        )
```

so this implies that `params.indir` and `wildcards.genomeA`/`wildcards.genomeB` are not being provided in a way that lets the workflow run. I'm continuing the invstigation.

**Comment by widdowquinn** [comment]
Found the problem. On l.107 what was `"indir": input_genomes_small,` should have been `"indir": str(input_genomes_small),` - the tests now pass.

**Comment by kiepczi** [comment]
>  I think we need to work on a consistent naming scheme for tests. 

My apologies for overlooking this. I'm currently working on this. Should I open a new issue for this?

**Comment by widdowquinn** [comment]
I'll correct problems raised by `ruff` and then push. We should be able to merge into `main` then - but we ought to address some of the inconsistencies in test function naming and set out our standardised process for naming, in the design docs.

**Comment by widdowquinn** [comment]
Related to #31, the CodeFactor analysis is showing up a security issue in the fixture-generating scripts. We should move from `os.system()` calls to something a bit more cautious.

**Comment by widdowquinn** [comment]
Merging after `ruff` problem fixes.

**Pull request merged**
