### PR TITLE
Drop duplicate tests

### PR DESCRIPTION
**Pull request by peterjc**
See discussion on #34. Reverts #50.

I've looked at the fastani test, and satisfied myself it was a near duplicate (only changes to the output path, and the number of cores).

### CODE REVIEW

**Comment by peterjc** [comment]
That's weird, ``OSError: [Errno 14] Bad address: '/bin/sh'`` from the Linux Python 3.12 tests.

I saw that once before on our Linux server during ``pytest -n ...`` testing. Perhaps a unwelcome side effect from #60.

**Comment by peterjc** [comment]
New profiling on my old 4-core iMac, as expected single threaded is much better - about halved:

```
$ pytest --durations=0 --durations-min=1.0
=========================== test session starts ============================
platform darwin -- Python 3.12.5, pytest-8.3.2, pluggy-1.5.0
rootdir: /Users/pc40583/repositories/pyani-plus
configfile: pyproject.toml
plugins: cov-5.0.0, xdist-3.6.1
collected 7 items                                                          

tests/snakemake/test_snakemake_anim_workflow.py ..                   [ 28%]
tests/snakemake/test_snakemake_dnadiff_workflow.py ....              [ 85%]
tests/snakemake/test_snakemake_fastani_workflow.py .                 [100%]

============================ slowest durations =============================
45.58s call     tests/snakemake/test_snakemake_dnadiff_workflow.py::test_snakemake_rule_show_diff
42.27s call     tests/snakemake/test_snakemake_dnadiff_workflow.py::test_snakemake_rule_show_coords
41.26s call     tests/snakemake/test_snakemake_dnadiff_workflow.py::test_snakemake_rule_filter
41.09s call     tests/snakemake/test_snakemake_anim_workflow.py::test_snakemake_rule_filter
38.65s call     tests/snakemake/test_snakemake_dnadiff_workflow.py::test_snakemake_rule_delta
38.36s call     tests/snakemake/test_snakemake_anim_workflow.py::test_snakemake_rule_delta
6.41s call     tests/snakemake/test_snakemake_fastani_workflow.py::test_snakemake_rule_fastani

(14 durations < 1s hidden.  Use -vv to show these durations.)
====================== 7 passed in 253.96s (0:04:13) =======================
```

Mutli-threaded seems to overwhelm the machine with too many mummer etc jobs at once. It feels worse than before - perhaps some luck in previously not having so many anim jobs at once? It certainly seems to make the machine works harder - but doesn't make much difference to the run time. Overall not recommended on a desktop machine:

```
$ pytest --durations=0 --durations-min=1.0 -n auto
============================= test session starts ==============================
platform darwin -- Python 3.12.5, pytest-8.3.2, pluggy-1.5.0
rootdir: /Users/pc40583/repositories/pyani-plus
configfile: pyproject.toml
plugins: cov-5.0.0, xdist-3.6.1
4 workers [7 items]     
.......                                                                  [100%]
============================== slowest durations ===============================
149.32s call     tests/snakemake/test_snakemake_dnadiff_workflow.py::test_snakemake_rule_filter
144.41s call     tests/snakemake/test_snakemake_dnadiff_workflow.py::test_snakemake_rule_delta
143.37s call     tests/snakemake/test_snakemake_anim_workflow.py::test_snakemake_rule_filter
142.43s call     tests/snakemake/test_snakemake_anim_workflow.py::test_snakemake_rule_delta
80.95s call     tests/snakemake/test_snakemake_dnadiff_workflow.py::test_snakemake_rule_show_coords
80.17s call     tests/snakemake/test_snakemake_dnadiff_workflow.py::test_snakemake_rule_show_diff
15.87s call     tests/snakemake/test_snakemake_fastani_workflow.py::test_snakemake_rule_fastani

(14 durations < 1s hidden.  Use -vv to show these durations.)
======================== 7 passed in 224.45s (0:03:44) =========================
```

**Comment by peterjc** [comment]
Profiling on the 24 core Linux machine:

```
$ pytest --durations=0 --durations-min=1.0
======================================= test session starts ========================================
platform linux -- Python 3.12.3, pytest-8.3.2, pluggy-1.5.0
rootdir: /home/pjacock/repositories/pyani-plus
configfile: pyproject.toml
plugins: cov-5.0.0, xdist-3.6.1
collected 7 items                                                                                  

tests/snakemake/test_snakemake_anim_workflow.py ..                                           [ 28%]
tests/snakemake/test_snakemake_dnadiff_workflow.py ....                                      [ 85%]
tests/snakemake/test_snakemake_fastani_workflow.py .                                         [100%]

========================================= warnings summary =========================================
tests/snakemake/test_snakemake_anim_workflow.py::test_snakemake_rule_filter
  /home/pjacock/miniforge3/envs/pyani-plus_py312/lib/python3.12/site-packages/stopit/__init__.py:10: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
    import pkg_resources

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
======================================== slowest durations =========================================
41.47s call     tests/snakemake/test_snakemake_dnadiff_workflow.py::test_snakemake_rule_show_coords
38.98s call     tests/snakemake/test_snakemake_dnadiff_workflow.py::test_snakemake_rule_show_diff
38.67s call     tests/snakemake/test_snakemake_dnadiff_workflow.py::test_snakemake_rule_filter
36.89s call     tests/snakemake/test_snakemake_dnadiff_workflow.py::test_snakemake_rule_delta
36.51s call     tests/snakemake/test_snakemake_anim_workflow.py::test_snakemake_rule_filter
36.39s call     tests/snakemake/test_snakemake_anim_workflow.py::test_snakemake_rule_delta
5.10s call     tests/snakemake/test_snakemake_fastani_workflow.py::test_snakemake_rule_fastani

(14 durations < 1s hidden.  Use -vv to show these durations.)
============================= 7 passed, 1 warning in 234.15s (0:03:54) =============================
```

Again, about halved.

And with pytest multi-threaded:

```
$ pytest --durations=0 --durations-min=1.0 -n auto
$ pytest --durations=0 --durations-min=1.0 -n auto
============================= test session starts ==============================
platform linux -- Python 3.12.3, pytest-8.3.2, pluggy-1.5.0
rootdir: /home/pjacock/repositories/pyani-plus
configfile: pyproject.toml
plugins: cov-5.0.0, xdist-3.6.1
24 workers [7 items]      
.......                                                                  [100%]
=============================== warnings summary ===============================
tests/snakemake/test_snakemake_fastani_workflow.py::test_snakemake_rule_fastani
tests/snakemake/test_snakemake_anim_workflow.py::test_snakemake_rule_delta
tests/snakemake/test_snakemake_dnadiff_workflow.py::test_snakemake_rule_delta
tests/snakemake/test_snakemake_dnadiff_workflow.py::test_snakemake_rule_filter
tests/snakemake/test_snakemake_anim_workflow.py::test_snakemake_rule_filter
tests/snakemake/test_snakemake_dnadiff_workflow.py::test_snakemake_rule_show_coords
tests/snakemake/test_snakemake_dnadiff_workflow.py::test_snakemake_rule_show_diff
  /home/pjacock/miniforge3/envs/pyani-plus_py312/lib/python3.12/site-packages/stopit/__init__.py:10: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
    import pkg_resources

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
============================== slowest durations ===============================
56.37s call     tests/snakemake/test_snakemake_dnadiff_workflow.py::test_snakemake_rule_show_diff
56.20s call     tests/snakemake/test_snakemake_dnadiff_workflow.py::test_snakemake_rule_show_coords
56.11s call     tests/snakemake/test_snakemake_anim_workflow.py::test_snakemake_rule_filter
54.78s call     tests/snakemake/test_snakemake_dnadiff_workflow.py::test_snakemake_rule_filter
52.85s call     tests/snakemake/test_snakemake_dnadiff_workflow.py::test_snakemake_rule_delta
51.95s call     tests/snakemake/test_snakemake_anim_workflow.py::test_snakemake_rule_delta
7.49s call     tests/snakemake/test_snakemake_fastani_workflow.py::test_snakemake_rule_fastani

(14 durations < 1s hidden.  Use -vv to show these durations.)
======================== 7 passed, 7 warnings in 58.26s ========================
```

Under a minute! 🎉

**Comment by kiepczi** [comment]
This might sound silly, so I apologise if it doesn’t make sense. For all workflows to run, we need to specify the number of cores required for the job. This is necessary for `snakemake` to distribute jobs efficiently, without the need for the extra long code we had in previous versions of `pyani`.

While writing `pytests`, I tested them on my local machine and specified 8 cores. For example, in [test_snakemake_anim_workflow.py](https://github.com/pyani-plus/pyani-plus/blob/drop_duplicate_tests/tests/snakemake/test_snakemake_anim_workflow.py), there is the following fixture where the number of core is specified and then fed to the `snakemake_scheduler.py` to distribute jobs:

```python
@pytest.fixture()
def config_filter_args(
    anim_nucmer_targets_filter_outdir: Path,
    input_genomes_small: Path,
) -> dict:
    """Return configuration settings for testing Snakemake filter rule.

    We take the output directories for the MUMmer filter output and the
    small set of input genomes as arguments.
    """
    return {
        "outdir": anim_nucmer_targets_filter_outdir,
        "indir": str(input_genomes_small),
        "cores": 8,
        "mode": "mum",
    }
```

If a different number of cores is specified elsewhere, could this create a conflict?

**Comment by peterjc** [comment]
I'm thinking we might want to change that number which is currently hard coded as 8.

For example, we might call a function like this one https://github.com/peterjc/thapbi-pict/blob/v1.0.13/thapbi_pict/__main__.py#L42 to use 8 if available, but capped to 4 if the system says only 4 are available (e.g. my old mac only has 4).

**Comment by kiepczi** [comment]
That would definitely help. 

I think both me and @widdowquinn have machines with 8 or more cores, and it didn't cross my mind this could be an issue.

**Comment by peterjc** [comment]
This is also important for "playing nicely" on a cluster where CPU limits are normal, and memory (RAM) limits are common.

**Review by widdowquinn — APPROVED** [review]

**Comment by widdowquinn** [comment]
That's great - thanks @peterjc !

**Pull request merged**
