### PR TITLE
Silence stdout during snakemake workflows

### PR DESCRIPTION
**Pull request by peterjc**
This PR runs snakemake in quiet mode (default is quite verbose), and since snakemake doesn't do it for us, also silences the underlying command line tools as well (which may not be necessary when run via a cluster).

The tool silencing is being done using the venerable Perl tool ``chronic`` (originally invented for use with ``cron``), which will capture and suppress the stdout/stderr provided the tool has a zero return code. If the tool fails, the output is restored.

This does add another dependency and point of failure, so I would prefer snakemake handled it - see https://github.com/snakemake/snakemake/issues/3152

Note that ``chronic`` is part of the ``moreutils`` package which is in conda-forge, but at the time of writing has an undeclared perl dependency provided by the ``perl-ipc-run`` package which is currently in bioconda only. That in turn needs ``perl-io-tty`` which is in conda-forge, but not yet packaged for ARM. See https://github.com/conda-forge/moreutils-feedstock/issues/6

A possible alternative is a new chronic implementation in go, which is not yet packaged for conda - https://github.com/docwhat/chronic

The motivation is for the main public facing command line interface (CLI), where I intend to use a progress bar alone (which with these changes works nicely in the non-error case).

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality not to work as expected)
- [ ] This change requires a documentation update
- [ ] This is a documentation update

## Action Checklist

- [x] Work on a single issue/concept (if there are multiple separate issues to address, please use a separate pull request for each)
- [x] Fork the `pyani-plus` repository under your own account (please [allow write access for repository maintainers](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork))
- [x] Set up an appropriate development environment (please see `CONTRIBUTING.md` for this repository)
- [x] Create a new branch with a short, descriptive name
- [x] Work on this branch
  - [x] style guidelines have been followed (please see `CONTRIBUTING.md` for this repository)
  - [x] new code is commented, especially in hard-to-understand areas
  - [ ] corresponding changes to documentation have been made
  - [ ] tests for the change have been added that demonstrate the fix or feature works
- [x] Test locally with `pytest-plus -v` **non-passing code will not be merged**
- [x] Rebase against `origin/master`
- [x] Check changes with linting/formatting tools before submission (please see `CONTRIBUTING.md` for this repository)
- [x] Commit branch
- [x] Submit pull request, describing the content and intent of the pull request
- [x] Request a code review
- [x] Continue the discussion at [`Pull requests` section](https://github.com/widdowquinn/pyani-plus/pulls) in the `pyan-plus` repository

### CODE REVIEW

**Comment by peterjc** [comment]
GitHub Actions failures under Linux:

```
BEGIN failed--compilation aborted at /home/runner/miniconda3/envs/pyani-github/bin/chronic line 37.
```

Says is it using:

```
moreutils-0.5.7            |                1          27 KB  bioconda
```

I did test this on our Linux server and its worked, but here I have version 0.67 from conda-forge. In my local copies of the script, line 37 is still part of the help text.

**Comment by widdowquinn** [comment]
The response at https://github.com/snakemake/snakemake/issues/3152 seems to have misunderstood your issue, and to think you want to log errors using `echo` <shrug />.

**Comment by widdowquinn** [comment]
Is it possible to avoid the additional dependency by wrapping calls to each tool in a function using `subprocess.run()`? I'm thinking that the function might:

1. checks the return code
2. log stdout/stderr to a `pyani-plus` logger if the return code is non-zero

That would give us flexibility to define return codes that are nonero but not in error, for any non-standard tools we might come across.

**Comment by widdowquinn** [comment]
Under https://docs.python.org/3/library/subprocess.html there is the note:

> If check is true, and the process exits with a non-zero exit code, a [CalledProcessError](https://docs.python.org/3/library/subprocess.html#subprocess.CalledProcessError) exception will be raised. Attributes of that exception hold the arguments, the exit code, and stdout and stderr if they were captured.

Can the main script see errors/logs from the workflow scripts?

**Review by widdowquinn — COMMENTED** [review]
Maybe we can avoid the additional dependency? (see notes above)

**Comment by widdowquinn** [comment]
Let's merge this in the interim, but with a view to testing the feasibility of the `subprocess.run(check=True)` -style wrapper, which may let us log tool run failures gracefully in the `pyani-plus` logger.

**Pull request merged**
