### PR TITLE
Support for containment mode in branchwater

### PR DESCRIPTION
**Pull request by peterjc**
The initial branchwater implementation only covered the default max-containment mode from sourmash. This extends it to match our sourmash support in offering non-symmetrical containment as well.

However, in doing this I felt the original approach was recording the transpose of the expected non-symmetrical containment matrix. I therefore transposed this, but really want a second or third opinion on this!

(As mentioned in person, with branchwater we get both the containment and max-containment at the same time - so could in principle record a double run in our DB to capture both. Or, we could perhaps record the max-containment as our identity value, and the query-containment and subject-containment as the query-coverage and subject-coverage? Those would then be transposes of each other? To discuss...)

## Type of change

- [x] Bug fix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality not to work as expected)
- [ ] This change requires a documentation update
- [ ] This is a documentation update

## Action Checklist

- [x] Work on a single issue/concept (if there are multiple separate issues to address, please use a separate pull request for each)
- [ ] Fork the `pyani-plus` repository under your own account (please [allow write access for repository maintainers](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork))
- [x] Set up an appropriate development environment (please see `CONTRIBUTING.md` for this repository)
- [x] Create a new branch with a short, descriptive name
- [x] Work on this branch
  - [x] style guidelines have been followed (please see `CONTRIBUTING.md` for this repository)
  - [x] new code is commented, especially in hard-to-understand areas
  - [ ] corresponding changes to documentation have been made
  - [x] tests for the change have been added that demonstrate the fix or feature works
- [x] Test locally with `pytest-plus -v` **non-passing code will not be merged**
- [x] Rebase against `origin/master`
- [x] Check changes with linting/formatting tools before submission (please see `CONTRIBUTING.md` for this repository)
- [x] Commit branch
- [x] Submit pull request, describing the content and intent of the pull request
- [x] Request a code review
- [x] Continue the discussion at [`Pull requests` section](https://github.com/widdowquinn/pyani-plus/pulls) in the `pyan-plus` repository

### CODE REVIEW

**Comment by widdowquinn** [comment]
Using query-coverage and subject-coverage to hold containment/subject containment scores, respectively, seems like a very good idea!

**Comment by peterjc** [comment]
As discussed in person: With classic sourmash, we could request containment mode and use the output and its transpose to record a query-coverage and subject-coverage, and their max would give us the max-containment output which we would record as percentage identity (as before).

Is there any point in recording both query-coverage and subject-coverage when they are each other's transpose by construction?

[With branchwater, for any pairwise comparison it outputs query-containment, subject-containment and max-containment explicitly.]

**Comment by widdowquinn** [comment]
I think examples with clear definitions would help understanding here - the containments themselves won't be transposes of each other, but matrices of them may be (if running the comparison in two directions).

**Comment by peterjc** [comment]
Possible example for testing query/subjection coverage/containment, relevant here to ensure the matrix isn't wrongly transposed, but also for methods like ANIm: [Vibrio cholerae](https://www.ncbi.nlm.nih.gov/datasets/taxonomy/666) two chromosomes and a plasmid: https://www.ncbi.nlm.nih.gov/datasets/genome/GCF_008369605.1/

**Comment by widdowquinn** [comment]
We need to be clear whether "query containment" for use means "proportion of query contained in the reference" or "proportion of reference contained in the query" ;)

**Comment by widdowquinn** [comment]
If we get the language sorted, I'm happy wiht max containment as "identity", and the other containments as the appropriate "coverage" (though we need to document this clearly for users).

**Comment by peterjc** [comment]
The merge conflict is minor, due to path changes in ``tests/fixtures/viral_example/intermediates/sourmash/sourmash.csv`` in 01b90130a3d95fc8366968e7afb8cfc7a8e7204e

I have been working on the approach of mapping the sourmash query-containment to our query-coverage, with sourmash max-containment mapped to our main percentage identity.

This would seem to confirm my intent to transpose ``sourmash.csv`` compared to our queries and row and subjects as columns interpretation [recall the matrix is symmetric for ``--max-containment`` mode, this only comes into play with ``--containment`` which will will map to coverage].

**Comment by peterjc** [comment]
Closing in favour of #211.

**Pull request closed without merging**
