### PR TITLE
ANIb snakemake workflow (fragment FASTA files, makeblastdb, blastn) - closes #13

### LINKED ISSUE #13: Create initial `snakemake` workflow for ANIb
To create initial `snakemake` workflow for `ANIb` method, we need to do the following:

1. Update the Makefiles to include the installation of `blast`.

2. Write Initial Workflow to Generate Appropriate Files. 

3. Create Test Set of Target Outputs.

4. Test the Workflow with `pytest`.

### PR DESCRIPTION
**Pull request by peterjc**
This closes #13, and includes the initial work on #85 which can be closed now.

This defines the basic snakemake workflow to:
* generate N fragmented FASTA files
* generate N nucleotide BLAST databases
* run the NxN pairwise blastn comparisons

The expected outputs can be regenerated via ``make fixtures``.

This PR does not parse the blastn tabular output to compute the ANIb identity and log this to the database (I am working on that though).

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality not to work as expected)
- [ ] This change requires a documentation update
- [ ] This is a documentation update

## Action Checklist

- [x] Work on a single issue/concept (if there are multiple separate issues to address, please use a separate pull request for each)
- [ ] Fork the `pyani-plus` repository under your own account (please [allow write access for repository maintainers](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork))
- [x] Set up an appropriate development environment (please see `CONTRIBUTING.md` for this repository)
- [x] Create a new branch with a short, descriptive name
- [x] Work on this branch
  - [x] style guidelines have been followed (please see `CONTRIBUTING.md` for this repository)
  - [x] new code is commented, especially in hard-to-understand areas
  - [x] corresponding changes to documentation have been made
  - [x] tests for the change have been added that demonstrate the fix or feature works
- [x] Test locally with `pytest-plus -v` **non-passing code will not be merged**
- [x] Rebase against `origin/master`
- [x] Check changes with linting/formatting tools before submission (please see `CONTRIBUTING.md` for this repository)
- [x] Commit branch
- [x] Submit pull request, describing the content and intent of the pull request
- [x] Request a code review
- [x] Continue the discussion at [`Pull requests` section](https://github.com/widdowquinn/pyani-plus/pulls) in the `pyan-plus` repository

### CODE REVIEW

**Comment by peterjc** [comment]
The Codeacy complaints are about the use of ``subprocess`` in the fixture generating script calling NCBI BLAST.

**Comment by peterjc** [comment]
We had a brief discussion about duplication of the FASTA generation code (in pyANI plus itself and the generate fixture script), vs self-contained bootstrapping and having this "fixed".

**Comment by widdowquinn** [comment]
Is that Codacy issue solved by wrapping the offending variable in `str()` (where it's currently a `Path`)?

**Comment by peterjc** [comment]
No change: "Detected subprocess function 'run' without a static string."

**Pull request merged**
