### PR TITLE
Record sourmash query-containment as query-coverage

### PR DESCRIPTION
**Pull request by peterjc**
Changes our sourmash and branchwater wrappers to always record max-containment as the ANI (which was the default mode), and record containment via the query-coverage matrix along side it.

To do this via ``sourmash compare`` (our ``sourmash`` method), we no longer run sourmash in ``--max-containment`` mode, but just in ``--containment`` mode and infer the max value for each query/subject pair.  This drops ``--mode max-containment`` or ``--mode containment`` as a user-facing option.

For our ``branchwater`` method, this just looks at an additional column from the output.

This PR also transposes the containment values from ``sourmash.csv`` before loading it as our query-coverage values. See discussion on #202 which this PR replaced, and the test case introduced on #212 which confirms this orientation is consistent.

## Type of change

- [x] Bug fix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality not to work as expected)
- [ ] This change requires a documentation update
- [ ] This is a documentation update

## Action Checklist

- [x] Work on a single issue/concept (if there are multiple separate issues to address, please use a separate pull request for each)
- [ ] Fork the `pyani-plus` repository under your own account (please [allow write access for repository maintainers](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork))
- [x] Set up an appropriate development environment (please see `CONTRIBUTING.md` for this repository)
- [x] Create a new branch with a short, descriptive name
- [x] Work on this branch
  - [x] style guidelines have been followed (please see `CONTRIBUTING.md` for this repository)
  - [x] new code is commented, especially in hard-to-understand areas
  - [x] corresponding changes to documentation have been made
  - [x] tests for the change have been added that demonstrate the fix or feature works
- [x] Test locally with `pytest-plus -v` **non-passing code will not be merged**
- [x] Rebase against `origin/master`
- [x] Check changes with linting/formatting tools before submission (please see `CONTRIBUTING.md` for this repository)
- [x] Commit branch
- [x] Submit pull request, describing the content and intent of the pull request
- [x] Request a code review
- [x] Continue the discussion at [`Pull requests` section](https://github.com/widdowquinn/pyani-plus/pulls) in the `pyan-plus` repository

### CODE REVIEW

**Comment by peterjc** [comment]
The interaction with the query-coverage test case and the other methods got complicated. I resurrected #210 as #212 to add the new test case and fix ANIb, fastANI and branchwater's handling of failed alignments.

I will rebase this on top of #212 now.

**Review by kiepczi — COMMENTED** [review]
It looks good to me. However, I feel it might be better if @widdowquinn also has a look at this. 

Also, just to clarify, will there no longer be an option for the end user to choose between different modes, like containment and max-containment? My apologies if I missed that.

**Comment by peterjc** [comment]
Yes - we loose the ``--mode max-containment`` versus ``--mode containment`` option. This is only an option in ``sourmash compare``, with sourmash branchwater's equivalent commands you get all of query-containment, subject-containment, and max-containment.

Mapping query-containment to query-coverage is a slight stretch, but a reasonable analogy. Leighton was OK with the _idea_ on Monday, but hasn't seen this code yet.

**Comment by peterjc** [comment]
This needed rebasing for the matrix label changes in #208.

**Comment by peterjc** [comment]
Reviewed in person with @kiepczi, merging now.

**Pull request merged**
