### PR TITLE
Add a resume command to the public API

### LINKED ISSUE #154: Add resume command to public CLI
Any of the methods will take a non-trivial time to run, so there is a chance of interruption. Perhaps more so with a cluster.

The database design avoids recomputing any pairwise ANI previously logged, so starting a new run will effectively resume (assuming same command is executed, via the shell history perhaps).

I am considering a new resume command taking only the database path and optionally run-id, defaulting to the most recent run. This will then check if any comparisons are missing, and if so run those after checking the command line dependency version matches that from the old run.

### PR DESCRIPTION
**Pull request by peterjc**
Closes #154.

This requires recording the input FASTA directory for each run in the database, and the FASTA filename too.

~~This works with the limitation that it will not handle cases where a FASTA was renamed from when it was first used in the database (and recorded with its original name, MD5 checksum, length etc in the genomes table), and then it was used in the run to be resumed.~~

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality not to work as expected)
- [ ] This change requires a documentation update
- [ ] This is a documentation update

## Action Checklist

- [x] Work on a single issue/concept (if there are multiple separate issues to address, please use a separate pull request for each)
- [ ] Fork the `pyani-plus` repository under your own account (please [allow write access for repository maintainers](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork))
- [x] Set up an appropriate development environment (please see `CONTRIBUTING.md` for this repository)
- [x] Create a new branch with a short, descriptive name
- [x] Work on this branch
  - [x] style guidelines have been followed (please see `CONTRIBUTING.md` for this repository)
  - [x] new code is commented, especially in hard-to-understand areas
  - [x] corresponding changes to documentation have been made
  - [x] tests for the change have been added that demonstrate the fix or feature works
- [x] Test locally with `pytest-plus -v` **non-passing code will not be merged**
- [x] Rebase against `origin/master`
- [x] Check changes with linting/formatting tools before submission (please see `CONTRIBUTING.md` for this repository)
- [x] Commit branch
- [x] Submit pull request, describing the content and intent of the pull request
- [x] Request a code review
- [x] Continue the discussion at [`Pull requests` section](https://github.com/widdowquinn/pyani-plus/pulls) in the `pyan-plus` repository

### CODE REVIEW

**Comment by peterjc** [comment]
I have two suggestions for handling renamed FASTA files.

1. We record the current filename in the run-genome linker table (and potentially drop the first-seen filename in the genome table)

Or,

2. Where the filenames don't match in resume mode, we scan the unmatched FASTA files in the input directory to compute their MD5, and use that to match which should be used.

**Comment by peterjc** [comment]
Note the DB schema change will break using old databases, e.g. trying to use ``list-runs`` fails with a colorful traceback via typer, ending with:

```
OperationalError: (sqlite3.OperationalError) no such column: runs.fasta_directory
[SQL: SELECT count(*) AS count_1 
FROM (SELECT runs.run_id AS runs_run_id, runs.configuration_id AS runs_configuration_id, runs.cmdline AS 
runs_cmdline, runs.fasta_directory AS runs_fasta_directory, runs.date AS runs_date, runs.status AS 
runs_status, runs.name AS runs_name, runs.df_identity AS runs_df_identity, runs.df_cov_query AS 
runs_df_cov_query, runs.df_aln_length AS runs_df_aln_length, runs.df_sim_errors AS runs_df_sim_errors, 
runs.df_hadamard AS runs_df_hadamard 
FROM runs) AS anon_1]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
```

**Comment by peterjc** [comment]
Emoji working nicely in the terminal, alignment slightly off here in the browser:

```console
$ pyani-plus list-runs --database pecto.db 
                    1 analysis runs in pecto.db                     
┏━━━━┳━━━━━━━━━━━━┳━━━━━━━━━┳━━━━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━━━━━━┓
┃ ID ┃ Date       ┃ Method  ┃ Comparisons ┃ Status   ┃ Name        ┃
┡━━━━╇━━━━━━━━━━━━╇━━━━━━━━━╇━━━━━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━━━━━━┩
│  1 │ 2024-10-31 │ fastANI │  94/784=28² │ Resuming │ 28 ⨉ Pba 🦠 │
└────┴────────────┴─────────┴─────────────┴──────────┴─────────────┘
$ pyani-plus resume  --database pecto.db 
INFO: Resuming run-id 1, the only run in the pecto.db
INFO: This is a fastANI run on 28 genomes, using fastANI version 1.33
Database already has 94 of 28x28=784 comparisons, 690 needed
host: Peters-iMac.local
Comparing pairs ╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   2% 0:00:12  17/690
```

**Comment by peterjc** [comment]
This now alters the DB schema to record the FASTA filename on the run-genome linker table as outlined on #75, and to record the FASTA directory in the run table.

**Comment by peterjc** [comment]
:warning: This has conflicts with the SLURM work on #158, and I lean towards merging that first.

**Comment by widdowquinn** [comment]
> Note the DB schema change will break using old databases, e.g. trying to use `list-runs` fails with a colorful traceback via typer, ending with:
> 
> ```
> OperationalError: (sqlite3.OperationalError) no such column: runs.fasta_directory
> [SQL: SELECT count(*) AS count_1 
> FROM (SELECT runs.run_id AS runs_run_id, runs.configuration_id AS runs_configuration_id, runs.cmdline AS 
> runs_cmdline, runs.fasta_directory AS runs_fasta_directory, runs.date AS runs_date, runs.status AS 
> runs_status, runs.name AS runs_name, runs.df_identity AS runs_df_identity, runs.df_cov_query AS 
> runs_df_cov_query, runs.df_aln_length AS runs_df_aln_length, runs.df_sim_errors AS runs_df_sim_errors, 
> runs.df_hadamard AS runs_df_hadamard 
> FROM runs) AS anon_1]
> (Background on this error at: https://sqlalche.me/e/20/e3q8)
> ```

I think we need to start using Alembic at this point: https://alembic.sqlalchemy.org/en/latest/

**Review by widdowquinn — CHANGES_REQUESTED** [review]
This looks very much on the way, just needing some conflict resolution and maybe a first use of Alembic?

**Comment by peterjc** [comment]
I added e12fb9c58b375a7d5f8588772397d881b49136da (adding ``runs.fasta_directory`` in the DB) directly to the main branch and rebased and cleaned up the rest into two commits (adding ``runs_genomes.fasta_filename`` to the DB, and adding the resume command).

**Comment by peterjc** [comment]
With this and #165 we now have several small DB schema changes, a good test case for ``alembic``...

**Pull request merged**
