### PR TITLE
Expected ANIb matrices computed with pyANI v0.2 - Issue 102

### PR DESCRIPTION
**Pull request by peterjc**
This is the first step to issue #102, still need to replicate the calculation of ANIb and then cross-check the resulting matrices against these.

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality not to work as expected)
- [ ] This change requires a documentation update
- [ ] This is a documentation update

## Action Checklist

- [x] Work on a single issue/concept (if there are multiple separate issues to address, please use a separate pull request for each)
- [ ] Fork the `pyani-plus` repository under your own account (please [allow write access for repository maintainers](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork))
- [x] Set up an appropriate development environment (please see `CONTRIBUTING.md` for this repository)
- [x] Create a new branch with a short, descriptive name
- [x] Work on this branch
  - [x] style guidelines have been followed (please see `CONTRIBUTING.md` for this repository)
  - [x] new code is commented, especially in hard-to-understand areas
  - [x] corresponding changes to documentation have been made
  - [ ] tests for the change have been added that demonstrate the fix or feature works
- [x] Test locally with `pytest-plus -v` **non-passing code will not be merged**
- [x] Rebase against `origin/master`
- [ ] Check changes with linting/formatting tools before submission (please see `CONTRIBUTING.md` for this repository)
- [x] Commit branch
- [x] Submit pull request, describing the content and intent of the pull request
- [ ] Request a code review
- [ ] Continue the discussion at [`Pull requests` section](https://github.com/widdowquinn/pyani-plus/pulls) in the `pyan-plus` repository

### CODE REVIEW

**Comment by peterjc** [comment]
Rebasing with commit message typo fixed ;)

**Comment by peterjc** [comment]
Given our discussion on #105 confirming that self-vs-self with ANIb may not give 100% query coverage, the coverage matrix here is "wrong". I see three options:

1. Update the pyani version_0_2 branch to compute self-vs-self for ANIb, and regenerate it
2. Tweak the coverage matrix recorded here as a manual and hopefully one-off change
3. Tweak the generator script to include duplicates of all the genomes in order to trick old pyani, and then compact the 6x6 matrix to the desired 3x3 matrix
4. Tweak the tests to ignore the ANIb coverage diagonal.

I lean towards option 4 as pragmatic and minimal effort, or option 1.

**Comment by peterjc** [comment]
Touch wood the self-vs-self coverage is OK on this example.

**Comment by peterjc** [comment]
Confirmed with pyani 0.2.13.1 using the 6x6 matrix, which sadly is not sorted:

```
$ xsv table output/ANIb_alignment_coverage.tab -d "\t"
                          OP073605            OP073605-again      MGV-GENOME-0266457-again  MGV-GENOME-0264574-again  MGV-GENOME-0266457  MGV-GENOME-0264574
OP073605                  1.0                 1.0                 0.6823144671500009        0.6773657709411174        0.6823144671500009  0.6773657709411174
OP073605-again            1.0                 1.0                 0.6823144671500009        0.6773657709411174        0.6823144671500009  0.6773657709411174
MGV-GENOME-0266457-again  0.9993180784967419  0.9993180784967419  1.0                       0.9787341516391372        1.0                 0.9787341516391372
MGV-GENOME-0264574-again  0.9972995694596591  0.9972995694596591  0.997860036175579         1.0                       0.997860036175579   1.0
MGV-GENOME-0266457        0.9993180784967419  0.9993180784967419  1.0                       0.9787341516391372        1.0                 0.9787341516391372
MGV-GENOME-0264574        0.9972995694596591  0.9972995694596591  0.997860036175579         1.0                       0.997860036175579   1.0
```

It would be worth noting which example Leighton tried which did give a self-vs-self coverage less than 100%...

**Comment by kiepczi** [comment]
I might be wrong, but I think it was bacterial and not the varial genomes that gave genome coverage of less than 100% for self-vs-self...

**Comment by peterjc** [comment]
If you're OK with it @kiepczi, I'd be happy to merge this PR now (just adding the expected matrices).

I think I'll have the final part doing the ANIb calculations and matrix testing ready this afternoon (which is worth keeping for Leighton to look over).

**Comment by kiepczi** [comment]
> Given our discussion on #105 confirming that self-vs-self with ANIb may not give 100% query coverage, the coverage matrix here is "wrong". I see three options:
> 
>     1. Update the pyani version_0_2 branch to compute self-vs-self for ANIb, and regenerate it
> 
>     2. Tweak the coverage matrix recorded here as a manual and hopefully one-off change
> 
>     3. Tweak the generator script to include duplicates of all the genomes in order to trick old pyani, and then compact the 6x6 matrix to the desired 3x3 matrix
> 
>     4. Tweak the tests to ignore the ANIb coverage diagonal.
> 
> 
> I lean towards option 4 as pragmatic and minimal effort, or option 1.

I would lean towards option 4 too. `pyANI v0.2` hasn't been maintained for a while, but I don't think I have a final say on this tbf :)

**Pull request merged**
