### PR TITLE
Export matrixes using filename stem labels by default

### PR DESCRIPTION
**Pull request by peterjc**
Follow on to #205 changing the default from MD5 labels (which remains the internal representation) to filename stems (matching legacy pyANI v0.3).

This required updating the expected matrices in the test fixtures and their generation scripts.

I had used MD5 initially partly as the earlier database schema did not explicitly record the FASTA filenames associated with a run.

Note currently duplicate input filename is impossible via the public CLI (since the input is a directory name), and duplicate stems (e.g. ``example.fna`` and ``example.fasta``) is treated as an error. Therefore should duplicate stems exist in the DB, that is treated as an error on export with the recommendation to use MD5 labeling instead.

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality not to work as expected)
- [ ] This change requires a documentation update
- [ ] This is a documentation update

## Action Checklist

- [x] Work on a single issue/concept (if there are multiple separate issues to address, please use a separate pull request for each)
- [ ] Fork the `pyani-plus` repository under your own account (please [allow write access for repository maintainers](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork))
- [x] Set up an appropriate development environment (please see `CONTRIBUTING.md` for this repository)
- [x] Create a new branch with a short, descriptive name
- [x] Work on this branch
  - [x] style guidelines have been followed (please see `CONTRIBUTING.md` for this repository)
  - [x] new code is commented, especially in hard-to-understand areas
  - [ ] corresponding changes to documentation have been made
  - [x] tests for the change have been added that demonstrate the fix or feature works
- [x] Test locally with `pytest-plus -v` **non-passing code will not be merged**
- [x] Rebase against `origin/master`
- [x] Check changes with linting/formatting tools before submission (please see `CONTRIBUTING.md` for this repository)
- [x] Commit branch
- [x] Submit pull request, describing the content and intent of the pull request
- [x] Request a code review
- [x] Continue the discussion at [`Pull requests` section](https://github.com/widdowquinn/pyani-plus/pulls) in the `pyan-plus` repository

### CODE REVIEW

**Comment by peterjc** [comment]
This will clash with #211 which changes the sourmash matrices, I suggest we merge that first and then I can address the conflict.

**Comment by peterjc** [comment]
New plan - while waiting for Leighton to look at #211, let's review and merge this @kiepczi (and I can rebase the sourmash work onto it)?

**Review by kiepczi — COMMENTED** [review]
My apologies for missing this yesterday! I somehow missed a email notification for this code review. 

Is my understanding correct that, we will still use hashes as internal IDs, and use stems only in reported matrices?

**Comment by peterjc** [comment]
Yes, nothing changes internally - still using MD5 hashes, so we can keep track of and re-use past computations even if the user renames their files.

This changes the default matrix export to label and sort by the FASTA filename stems, and changed all the expected matrices in the test fixtures to do that too.

**Pull request merged**
