### PR TITLE
Self-vs-self tests where not 100% identity

### PR DESCRIPTION
**Pull request by peterjc**
This adds two minimal tests cases (two different contigs from real assemblies) where ANIm and fastANI give less than 100% identity.

I would like to add a similar test for ANIb but have not found one yet. On #105 we discussed a 4MB bacteria where this happened. I tried a few artificial examples with a large run of N into a sequence but have yet to get this to work.

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality not to work as expected)
- [ ] This change requires a documentation update
- [ ] This is a documentation update

## Action Checklist

- [x] Work on a single issue/concept (if there are multiple separate issues to address, please use a separate pull request for each)
- [ ] Fork the `pyani-plus` repository under your own account (please [allow write access for repository maintainers](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork))
- [x] Set up an appropriate development environment (please see `CONTRIBUTING.md` for this repository)
- [x] Create a new branch with a short, descriptive name
- [x] Work on this branch
  - [x] style guidelines have been followed (please see `CONTRIBUTING.md` for this repository)
  - [x] new code is commented, especially in hard-to-understand areas
  - [ ] corresponding changes to documentation have been made
  - [x] tests for the change have been added that demonstrate the fix or feature works
- [x] Test locally with `pytest-plus -v` **non-passing code will not be merged**
- [x] Rebase against `origin/master`
- [x] Check changes with linting/formatting tools before submission (please see `CONTRIBUTING.md` for this repository)
- [x] Commit branch
- [x] Submit pull request, describing the content and intent of the pull request
- [x] Request a code review
- [x] Continue the discussion at [`Pull requests` section](https://github.com/widdowquinn/pyani-plus/pulls) in the `pyan-plus` repository

### CODE REVIEW

**Comment by widdowquinn** [comment]
I think @kiepczi has an example ANIb comparison run with non-100% match… maybe she can provide the accessions?

**Comment by widdowquinn** [comment]
If we've only tried engineering faiure with long runs of Ns with ANIb, maybe scattering them might give a different result?

**Comment by peterjc** [comment]
Cross reference https://github.com/ParBLiSS/FastANI/issues/132 for fastANI not always giving 100% identity for self-vs-self, where the fragment length can be important.

**Comment by widdowquinn** [comment]
I can see why MIBY01000005.1 fails (run of Ns) but I don't see why MIBY01000011.1 does - confusing!

**Comment by peterjc** [comment]
I have thus far failed to get anything but 0% or 100% from ANIb on self-tests by adding base N to a sequence (runs or scattered).

**Pull request merged**
